name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: coursier/setup-action@v1.2.0-M2
        with:
          jvm: temurin:1.21
          apps: sbt
      - name: Test
        run: sbt clean test scripted
